# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rLancet <- function(tumor_bam, normal_bam, ref_fasta, reg, bed_file, numthreads) {
    .Call('_RLancet_rLancet', PACKAGE = 'RLancet', tumor_bam, normal_bam, ref_fasta, reg, bed_file, numthreads)
}

rcpp_hello_world <- function() {
    .Call('_RLancet_rcpp_hello_world', PACKAGE = 'RLancet')
}

